### ISSUE TITLE
定理疑惑

### ISSUE THREAD

**Issue by hadis-ye** [Haoqing-Wang/InfoCL#1]
![image](https://user-images.githubusercontent.com/51023285/163664581-5d1492c7-dac1-4925-b9d8-452eb655b555.png)
![Uploading image.png…]()

能否求证一下作者，这两个错误率的公式从何而来，有没有什么相关资料提供。为什么beyes error 用1-exp()去计算，不太理解，回归预测的平方误差也需要用exp(.)能否提供解答，感谢

**Comment by Haoqing-Wang** [comment]
您好，下游任务的误差率实际上和条件熵H(T|z)直接相关，其中贝叶斯误差率满足P_e<=1-exp(-H(T|z))，请参考论文《Relations between entropy and error probability》，最小平方误差满足R_e=a·exp(2H(T|z))，请参考论文《Is mutual information adequate for feature selection in regression?》。我们在附录中的引理2中提供了各种表示在下游任务的条件熵H(T|z)的表达式，将他们直接带入上述关系即可得到正文中的定理1和定理2.

**Comment by hadis-ye** [comment]
好的谢谢您
