### ISSUE TITLE
优化函数的两种修改方式

### ISSUE THREAD

**Issue by hadis-ye** [Haoqing-Wang/InfoCL#2]
![image](https://user-images.githubusercontent.com/51023285/163678273-616cde85-7945-4218-8ae2-4b7ce146878c.png)
![image](https://user-images.githubusercontent.com/51023285/163678281-f25f7a9b-ddab-4f31-9180-da7cce886ddb.png)
抱歉这么晚还打扰您，能否麻烦您对这两个公式的细节进行讲解（或者能够提供方向，让我自己去研究），不知道是否因为知识存储量还不够，所以看不懂！

**Comment by Haoqing-Wang** [comment]
你好，这两个公式都是把正态分布的表达式直接代入指定的式子即可。比如第一个公式可以直接把q(v|z)=N(\mu(z), \sigma^2)带入公式（11）左边的表达式，第二个式子是把p(z|v)=N(f(v), \sigma^2)带入论文中的公式（13）即可，这里注意因为\sigma是常数，所以省略了。需要的知识储备大概就是概率论那些东西。
