### ISSUE TITLE
About ImageNet training

### ISSUE THREAD

**Issue by ark1234** [Haoqing-Wang/InfoCL#3]
Thank you for your amazing results, I have a question on your ImageNet's training,  I tried your RC method with 4 A100 80GB GPUs, the GPU memory is not enough, and GPU usage is very imbalanced. Could you tell me your PyTorch version and training specifications (like how many GPUs and GPU model). Many thanks!

**Comment by Haoqing-Wang** [comment]
Thanks for your interesting in our work. In fact, I forget to use data parrall for **recon** module when training on ImageNet in the released code, sorry for that. You may need to add this comment to `main.py` in proper position.
`
if args.dataset=='ImageNet':
recon = torch.nn.DataParallel(recon, device_ids=list(range(args.gpus)))
`

**Comment by ark1234** [comment]
Thank you so much, I will have a try and let you know the results!
