### ISSUE TITLE
对bayes error rate的疑惑

### ISSUE THREAD

**Issue by Aknifejackzhmolong** [Haoqing-Wang/InfoCL#4]
![image](https://user-images.githubusercontent.com/23431216/191415853-9eede328-5324-4074-bee0-d9b4e04ffaa1.png)
在您百忙之中打扰了，请问一下这个贝叶斯错误率和InfoMin中的missing info是不是指的一回事，表示实际上最小有效representation捕获的信息不充分，然后最小有效编码器会扩大这一问题，不知我的理解对不对。
![image](https://user-images.githubusercontent.com/23431216/191416153-38c01f45-b617-4b02-92ea-649a0eb7b24e.png)
如果多个view包含的互信息中，任务相关信息已经充分到能够完成分类任务，那么这个多出来的H(T|z)有没有可能只是冗余特征的信息量。
还有个问题就是只有任务相关信息会影响贝叶斯错误率吗，任务无关的信息在增大 $I(z^{sup}_1,v_1|v_2)$ 的过程中也会引入把，这不会影响贝叶斯错误率吗？

**Comment by Haoqing-Wang** [comment]
1.贝叶斯误差率和missing info差不多一个意思，都是说view共享的信息不充分；
2.H(T|z)是给定表示的情况下预测分布的熵，表示不确定程度，一般越小越好。但不是冗余信息；
3.只有任务相关的信息会影响贝叶斯误差率，其他任务无关的信息会增加需要使用的训练样本量。但是我们发现实际中的view共享信息并不够，还没到冗余的状态，所以应该进一步增加。
