### ISSUE TITLE
缺少权重文件

### ISSUE THREAD

**Issue by youzi260** [Haoqing-Wang/InfoCL#5]
您好，我在运行det_seg代码块时，并没有找到Pretrain_Name.pt这个文件，能否提供一下这个权重文件？

“Convert a pre-trained model to detectron2's format:

python convert.py pretrain/Pretrain_Name.pt pretrain/Pretrain_Name.pkl“

**Comment by Haoqing-Wang** [comment]
您好，预训练之前在公司做的，checkpoint没保存下来。我现在已经不在微软实习了，很抱歉无法提供。
